In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Sample data
data = np.array([[10, 2.7, 3.6],
                 [-100, 5, -2],
                 [120, 20, 40]], dtype=np.float64)

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Normalize the data
normalized_data = scaler.fit_transform(data)

print("Normalized Data:\n", normalized_data)

Normalized Data:
 [[0.5        0.         0.13333333]
 [0.         0.13294798 0.        ]
 [1.         1.         1.        ]]


In [2]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the data
standardized_data = scaler.fit_transform(data)

print("Standardized Data:\n", standardized_data)

Standardized Data:
 [[ 0.         -0.85170713 -0.55138018]
 [-1.22474487 -0.55187146 -0.852133  ]
 [ 1.22474487  1.40357859  1.40351318]]


In [3]:
from sklearn.model_selection import train_test_split

# Define features and target
X = np.random.rand(100, 5)
y = np.random.randint(0, 2, 100)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)

Training Features Shape: (70, 5)
Testing Features Shape: (30, 5)


In [4]:
# Step 1: Normalizing the Data
# Using MinMaxScaler to scale features to [0, 1] range.

import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([...])
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(data)

# Step 2: Splitting Dataset
# Using sklearn's train_test_split for splitting

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(...)

TypeError: float() argument must be a string or a real number, not 'ellipsis'